- hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Clone TravelMemory repo
      git:
        repo: https://github.com/JOYSTON-LEWIS/Assignment_10_DevOps
        dest: /home/ubuntu/travelmemory

    - name: Install backend dependencies
      shell: npm install
      args:
        chdir: /home/ubuntu/travelmemory/backend

    - name: Install frontend dependencies
      shell: npm install
      args:
        chdir: /home/ubuntu/travelmemory/frontend

    - name: Start backend and frontend
      shell: |
        nohup npm start &
      args:
        chdir: /home/ubuntu/travelmemory/backend
